---

dependency:
  name: galaxy

driver:
  name: vagrant

platforms:
  - name: instance-${MOLECULE_ROLE_NAME:-molecule}-1
    interfaces:
      - network_name: forwarded_port
        guest: 8080
        host: 8080
    groups:
      - kafka
      - zookeeper
    box: williamyeh/centos7-docker
    memory: 1024
    cpus: 1

provisioner:
  name: ansible
  log: true
  options:
    become: true
    vvv: false
  inventory:
    group_vars:
      all:
        molecule_testing: True

verifier:
  name: ansible
